name: dw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: any
  go_router: ^14.0.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/preview/
    - assets/infoblock/
    - assets/test/
    - assets/infoblock/
